name: Python CI

on:
  push:
    branches: [main]  # or other branches you want to trigger the CI on
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build the package or install from source
    - name: Build project
      run: |
        python setup.py install  # This will generate the 'build' directory (or another custom build step)

    # Step 5: Run tests
    - name: Run tests with pytest
      run: |
        pytest tests/test_functions.py  # Or simply 'pytest' to run all tests